### ISSUE TITLE
Dead guides link

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-mailpit#12]
Looks like the extension got released with a dead guides link, https://quarkiverse.github.io/quarkiverse-docs/quarkus-mailpit/dev/ . 

To fix, should we remove the link or publish the docs?

**Comment by melloware** [comment]
We should publish the docs?  I thought I had submitted the PR's to extensions catalog correctly?

**Comment by holly-cummins** [comment]
There's another step for docs. 🤦‍♀️ It's [documented](https://hub.quarkiverse.io/), but only if you know where to look.
"To register your extension's documentation, open a PR including it in the [antora-playbook.yml](https://github.com/quarkiverse/quarkiverse-docs/blob/main/antora-playbook.yml)"

I'm more and more thinking that we should do something to make all this easier, though. More-easily findable docs is part of it, but the best docs are the docs you don't even need.

**Comment by melloware** [comment]
Done!  I am a moron: https://github.com/quarkiverse/quarkiverse-docs/pull/116/files

**Comment by melloware** [comment]
Thanks its there now!

**Comment by holly-cummins** [comment]
Thanks!
