### ISSUE TITLE
Mailpit not starting if only @MailerName configs are used

### ISSUE THREAD

**Issue by wansors** [quarkiverse/quarkus-mailpit#17]
The Mailpit services are not started if no default mail config is used.

If I only use @MailerName configurations:
`%dev.quarkus.mailer.smtp1.host=localhost
%dev.quarkus.mailer.smtp1.port=1025
%dev.quarkus.mailer.smtp1.mock=false
%dev.quarkus.mailer.smtp1.from=from-stmpt1@quarkus.io`

The Mailpit services are not started giving the error:

`2023-10-19 09:55:57,176 WARN  [io.qua.mai.dep.MailpitProcessor] (build-10) Not starting dev services for Mailpit, as no 'quarkus.mailer.port' has been configured.`

**Comment by melloware** [comment]
@all-contributors add @wansors for bug
