### ISSUE TITLE
Dev UI gives `Error sending data to the server. Please try again.` when the app is reloaded

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-mailpit#21]
Steps to reproduce: 
- Create an application as instructed in https://docs.quarkiverse.io/quarkus-mailpit/dev/index.html#_usage
- Hit http://localhost:8080/superheroes to send an email to Mailpit.
- In a separate tab, go to http://localhost:8080/q/dev-ui/io.quarkiverse.mailpit.quarkus-mailpit/mailpit-ui and click on the "Inbox" link
- Change the Resource (or `application.properties`) and hit http://localhost:8080/superheroes again.
- Navigate to the tab and **without refreshing** click on the "Inbox" link.

You should get the following error: 

![image](https://github.com/quarkiverse/quarkus-mailpit/assets/54133/4a0eaf87-fb17-4630-9e4d-01c1f9d63a92)

Refreshing the page makes the link work again, but it's a bit annoying :)

**Comment by phillip-kruger** [comment]
You can detect hotreload in Dev UI: https://quarkus.io/guides/dev-ui-v2#hot-reload

In the `hotreload` method you can add code to restore state after a hot reload

**Comment by melloware** [comment]
Awesome I knew you would have awesome trick for me!
