### ISSUE TITLE
Configure Mailpit port

### ISSUE THREAD

**Issue by georgleber** [quarkiverse/quarkus-mailpit#50]
Hi all,

in the documentation at https://docs.quarkiverse.io/quarkus-mailpit/dev/index.html is mentioned how to to configure dev-mailer:

```
%dev.quarkus.mailer.host=localhost
%dev.quarkus.mailer.port=1025
%dev.quarkus.mailer.mock=false
```

But when starting Quarkus, Mailpit is changing port on every start. So I need to set the port (`https://docs.quarkiverse.io/quarkus-mailpit/dev/index.html`) on every start. What am I missing?

**Comment by melloware** [comment]
oh i need to update the docs.  You can remove...

```
%dev.quarkus.mailer.host=localhost
%dev.quarkus.mailer.port=1025
%dev.quarkus.mailer.mock=false
```

At Dev time we autodetect and wire up the mailer correctly to the correct dynamic port for you!

Basically you can just run and it will work. Let me know how it goes.

**Comment by melloware** [comment]
@all-contributors add @georgleber for docs
