### ISSUE TITLE
Using MailClient mails are not send to Mailpit mailbox

### ISSUE THREAD

**Issue by georgleber** [quarkiverse/quarkus-mailpit#53]
I need to send mails via the underlying `io.vertx.ext.mail.MailClient` because my SMTP provider can be configured by the user of my application. In the dev environment I would like to use the mailpit extension, but sending mails with `MailClient` does not end in the mailbox. 

Is there anything I need to configure?

```
    MailMessage message = new MailMessage();
        
    message.setFrom(sender);
    message.setTo(Arrays.asList(recipients));
    message.setSubject(subject);
    message.setText(textContent);
    message.setHtml(htmlContent);

    mailClient.sendMail(message);
```

**Comment by melloware** [comment]
@georgleber i just wrote an integration test with `Vertx.MailClient` and it passes just fine using Mailpit.

See commit: https://github.com/quarkiverse/quarkus-mailpit/commit/4f2a269372d8bb9ba1600f00d7040a58e823c973

**Comment by melloware** [comment]
Actually no it does fail.  According to this it should be the same as Injecting Mailer but its clearly not.

https://quarkus.io/guides/mailer-reference#using-the-underlying-vert-x-mail-client

**Comment by melloware** [comment]
OK it definitely works with Vertx.client just fine.

![image](https://github.com/quarkiverse/quarkus-mailpit/assets/4399574/7476b6f8-a27b-4553-aa34-3165ea0a669c)

**Comment by georgleber** [comment]
Hi @melloware 

I have tested it a little further now and it works. My problem was, that I configured `quarkus.mailer` in `application.yml`.
As I moved it into "%prod" block it works now.

**Comment by melloware** [comment]
Awesome yeah once it detects you are using a real mail server MailPit does not configure itself.
