### ISSUE TITLE
Send mail hangs with MailPit installed

### ISSUE THREAD

**Issue by tmulle** [quarkiverse/quarkus-mailpit#6]
Using this simple code, two things happen:

If I use the commented out code only, then Quarkus blows up with a "sender address not found"

If I set `quarkus.mailer.from` in the application properties to my email, when I hit it with `curl` it hangs and I have to hit Ctrl-C to kill the curl.

```java
@Path("/mail")
public class MailResource {

    @Inject
    Mailer mailer;

    @GET
    @Blocking
    public void sendEmail() {
        
        Mail m = new Mail();
        m.setFrom("YOUR_EMAIL_ADDRESS");
        m.setTo(List.of("quarkus@quarkus.io"));
        m.setText("A simple email sent from a Quarkus application.");
        m.setSubject("Ahoy from Quarkus");
        mailer.send(m);
//        mailer.send(
//                Mail.withText("quarkus@quarkus.io",
//                        "Ahoy from Quarkus",
//                        "A simple email sent from a Quarkus application."
//                )
//        );
    }
}
```

Replace `YOUR_EMAIL_ADDRESS` with a valid sender email.

I tried to explicitly set the mail settings and send that and the same thing, it just hangs (with no errors)

if I don't use the MailPit extension, the mailer works fine without setting the sender address

Reproducer: https://github.com/tmulle/quarkus-mailpit-test

**Comment by melloware** [comment]
That would surprise me unless it is a bug in MailPit?

**Comment by melloware** [comment]
The code here is just treating the server as an SMTP protocol server so I can't imagine why it would hang?

**Comment by melloware** [comment]
Also what does @blocking do??

**Comment by melloware** [comment]
OK I wrote an integration test and its passing with a real email address in the from:

![image](https://github.com/quarkiverse/quarkus-mailpit/assets/4399574/f2e587dd-0566-4bdd-a685-f5aefdc934fd)

**Comment by melloware** [comment]
@all-contributors add @tmulle for testing

**Comment by tmulle** [comment]
Ok, so the issue appears to be with M1 Mac and Docker Desktop.

For some reason, the container didn't throw an address in use for port 1025 when in fact the port was already in use by `Synology Drive Agent` running on my mac.

Doing a `sudo lsof -i -P | grep LISTEN | grep :1025` found that the `FinderSync` application was running on port `1025` already.

Killing the `FinderSync` process or choosing a different port for the `mailpit` extension fixed the issue and the process no longer hangs when sending mail via standard or reactive mailer.

Just for further knowledge. Case is closed.
