### ISSUE TITLE
DevUI: Card is lost when live reload

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-mailpit#64]
@phillip-kruger maybe you can help me debug why this happens.  Whenever you make a code change the Dev Card is lost.  

### Normal Startup:
![image](https://github.com/quarkiverse/quarkus-mailpit/assets/4399574/ed564f58-979d-4514-952b-9e4281c39b9f)

### After Live Reload:
![image](https://github.com/quarkiverse/quarkus-mailpit/assets/4399574/027bdf5b-e93d-4a73-b6c0-1bc1e622b14a)

**Comment by phillip-kruger** [comment]
That is a weird one! I'll have a look

**Comment by melloware** [comment]
Thanks for the fix!!
