### ISSUE TITLE
A possibility to configure the smtp Port in DevService

### ISSUE THREAD

**Issue by horst-laubenthal** [quarkiverse/quarkus-mailpit#70]
We are using a keycloak dev-service that is able to send emails. To configure our realm import with proper smtp config, it would be nice if there would the possibility to have a fixed port to be configured.
Or to be more convenient, would it be possible if you use the property: quarkus.mailer.port=... if it is set?

**Comment by melloware** [comment]
I was doing this before but @ggrebert helped refactor the code to be more dynamic and this feature was lost.  @ggrebert do you think the request above is still possible?  That was my original intent in the first version.

**Comment by melloware** [comment]
@all-contributors add @horst-laubenthal for ideas

**Comment by melloware** [comment]
@horst-laubenthal 1.1.0 is in Maven Central.  Can you try it now?  It should be looking for your `quarkus.mailer.port` and configuring that?

**Comment by horst-laubenthal** [comment]
Works! Thank you!
