### ISSUE TITLE
Change mailpit URL exposed in Dev UI?

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-mailpit#79]
I notice in the Dev UI that when clicking the Mailpit UI link the URL brings you to a `127.0.0.1` URL.

Is it possible to change the host name in the URL? In cloud-based IDEs (like Eclipse Che, Gitpod, etc), the URL in the browser can't be `127.0.0.1`/`localhost`. It needs to be a URL where the port can be mapped to the URL of the workspace.

**Comment by melloware** [comment]
@ggrebert do you know if the above request is a limitation of TestContainers or Quarkus?

**Comment by ggrebert** [comment]
It's not a TestContainer limitation.
TestContainer forward the MailPit port (`8025`) to dynamic one.
The real problem is the hostname. We need to change `localhost` to the real hostname.
I need to check to an existing working extension on `Eclipse Che` to check how is it done.

**Comment by gsmet** [comment]
Could it be something similar to https://github.com/quarkusio/quarkus/pull/42065 ?

(I haven’t looked at the issue, just connecting the dots on my phone…)

**Comment by ggrebert** [comment]
The shared network is used for the communications between containers.
I have fixed this issue by adding a proxy which allow the access to the Mailpit UI on the same port of Quarkus.

**Comment by edeandrea** [comment]
Nice! Would this change make #82 irrelevant? Or do you think having a way to configure a fixed port mapping is still a relevant use case?

**Comment by melloware** [comment]
@edeandrea honestly i never know someone's use case so having it configurable is fine with me.  I am sure someone else will ask for it down the road because they have 8025 in use by some other app or something!

**Comment by ggrebert** [comment]
Agree.
It is always better to use the dynamic port created by TestContainer to be agnostic of the dev local configuration.
But we cannot known the needs of everyone.
So we can keep it and just encourage the proxy usage.

**Comment by melloware** [comment]
I made a few minor fixes: https://github.com/quarkiverse/quarkus-mailpit/pull/85

**Comment by edeandrea** [comment]
> 1.2.0 is in Maven Central @edeandrea if you want to give it a spin?

I'll give it a spin in a little bit! Just sitting down to start my day!

**Comment by edeandrea** [comment]
Works like a charm! Didn't even need to use the fixed port feature! The link from the dev ui works fine, plus by adding it to the che devfile's endpoints I can access it directly from eclipse che...

![image](https://github.com/user-attachments/assets/05643e94-a83c-4c7b-9391-7b3ea1d4376a)

**Comment by melloware** [comment]
Excellent!!!

**Comment by edeandrea** [comment]
Thank you both for the quick turnaround!
