### ISSUE TITLE
"Fix" the mapped port of mailpit container?

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-mailpit#80]
Is there a way to "fix" the exposed port of the mailpit container? In cloud-based IDEs (like Gitpod/Eclipse Che/etc) we need to know ahead-of-time which ports can be exposed/exported from the localhost. It seems to be randomly generated?

It would be nice to have a config item which could fix the port on a value the user provides.

**Comment by melloware** [comment]
Exposed SMTP port or the HTTP port?

**Comment by edeandrea** [comment]
HTTP port

**Comment by melloware** [comment]
Nope I will add this feature!

**Comment by melloware** [comment]
@all-contributors add @edeandrea for idea

**Comment by edeandrea** [comment]
Awesome! If its not something that you can get to shortly I can probably do a PR in a day or two.

**Comment by melloware** [comment]
I should have no problem doing it.  You can start researching the other issue!

**Comment by edeandrea** [comment]
I'm actually almost done :)

**Comment by melloware** [comment]
Oh cool submit it then!

**Comment by melloware** [comment]
I assigned it to you.
