### ISSUE TITLE
Question - why do all the Mailbox methods throw `ApiException`?

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-mailpit#87]
I find it very hard to use because all the methods on `Mailbox` throw `ApiException`, which is a checked exception. It reminds me of things in the `java.io` and `java.sql` packages. It also makes using streams/lambdas/etc very difficult.

Could/should `ApiException` be a `RuntimeException`? I see that the class is generated, so if there isn't a way to have it generated as a runtime exception, maybe invent another one and then add the try/catch/re-throw to the methods in `Mailbox`?

**Comment by melloware** [comment]
good question i just use OpenAPI Generator to generate from Mailpit Swagger Doc.  I will look into it.

**Comment by melloware** [comment]
OK 1.2.1 is deployed if you want to test it out.

**Comment by edeandrea** [comment]
Works like a charm! Was completely backwards-compatible. IntelliJ had notices that I didn't need to catch/throw `ApiException`, but didn't fail to compile/run if I left it. Also was fine after removing.

https://github.com/rh-rad-ai-roadshow/parasol-insurance/commit/ceec8c7178ab1f7f077fd200ed721806114ed5d1

**Comment by melloware** [comment]
awesome thanks for testing!

**Comment by edeandrea** [comment]
Thanks again for the quick turnaround!
