### ISSUE TITLE
Capture email when running in Test profile?

### ISSUE THREAD

**Issue by flowt-au** [quarkiverse/quarkus-mailpit#93]
Hi. 
Thanks for this really helpful extension.

I note the docs say: `for testing or running in dev mode`, which certainly works really well.

I wanted to use it to capture emails generated by my tests.

I have the `quarkus-mailpit-testing` in my pom.xml (v1.2.2).

I tried it (with `%test.quarkus.mailer.mock=true`, explicitly, or using the default) and mock=false (just in case), and no email shows up in MailPit either way.

Am I right in saying that if my tests generate emails (i.e. when running tests using the Quarkus integrated test runner), the extension wont capture them to MailPit?

I am using the `io.quarkus.mailer.reactive.ReactiveMailer`.

I have annotated my tests as per the example in case it needed that to capture the email in the first place.
```java
@WithMailbox
...
    @InjectMailbox
    Mailbox mailbox;
```

Hmmm.... in DEV mode, the emails arrive. In TEST mode, running the same code, there are no errors and no email. I am not sure what to expect here.

Thanks,
Murray

**Comment by melloware** [comment]
@flowt-au check out our Integration Tests project...  https://github.com/quarkiverse/quarkus-mailpit/tree/main/integration-tests

You will see the tests run and capture the emails and verify them.

https://github.com/quarkiverse/quarkus-mailpit/blob/main/integration-tests/src/test/java/io/quarkiverse/mailpit/it/MailpitResourceTest.java

**Comment by melloware** [comment]
Let me know what you find out comparing how are tests are running vs why yours are not.  A note ours is not use Reactive so maybe that is the difference but I wouldn't think so.

**Comment by flowt-au** [comment]
Ok, I will run up a standalone example then compare to mine. 

Also, my use-case is to actually see the email in the MailPit UI. The reason is I use the "red-green" pattern and start development with the tests. The email generation is just one step in a long pipeline. So, to get the email looking the way I want I use the test of the pipeline as the "development environment" to generate then visually check the layout and content. It would be tricky and time-consuming to write a test the check the layout! 

It occurs to me that since the tests run on a different port than the DEV profile, maybe that is why I cannot see them in MailPit on my dev port. I will write a test to check for presence like the sample you describe, and get back to you.

Thanks,
Murray

**Comment by flowt-au** [comment]
Ok. I see the issue. In my sleepy state I was expecting the email to be visually present in the MailPit UI. Doh!

By adding these lines to my test
```java
Message message = mailbox.findFirst("mytest@test.com.au");
System.out.println("message: " + message.toString());
```
I can see the email in the terminal.

And, when I generate the email I add a line with the LaunchProfile string so I know if it was TEST or DEV that created it. 

For my DEV run it says `App is running under DEVELOPMENT profile.` and for the test it says `App is running under TEST profile.`. Of course.

All good. Now I have the pipeline working I can just use my dev runs to fine tune the layout of the email.

**BTW:** The docs example [here](https://quarkus.io/guides/mailer-reference#testing) has the following in the test:
```java
List<Mail> sent = mailbox.getMessagesSentTo(TO);
```
but that throws `The method getMessagesSentTo(String) is undefined for the type Mailbox` (and I am using io.quarkiverse.mailpit.test.Mailbox)

Thanks again,
Murray

**Comment by melloware** [comment]
That is Mock Mailbox docs.  you are NO LONGER using MockMail once you use Mailpit.  Follow my Testing Docs.
